theme: jekyll-theme-slate
title:  Yuxin Chen
description:  <p>ğŸ“ <a href="tel:+8615666202656">+86 156 6620 2656</a> ğŸ“§ <a href="mailto:yuxinchennn@163.com">yuxinchennn@163.com</a></p>
<p>ğŸ  No. 1188, East Dongyue Road, Lingshanwei Subdistrict, Huangdao District, Qingdao, Shandong, 266555, China</p>